<?php
namespace App;
use App\http\MyContext;

class MyRouter extends \FastRoute\RouteCollector
{
   public function add($httpMethod, $route, $handler)
   {
       $func=function (MyContext $context) use($handler){

           return $handler($context);
       };
       parent::addRoute($httpMethod, $route, $func); // TODO: Change the autogenerated stub
   }
}