<?php
namespace App;

use App\http\MyContext;

class MyRouter extends \FastRoute\RouteCollector
{
    private $handlers=[];
   public function add($httpMethod, $route,...$handlers)
   {
       $this->handlers=array_merge($this->handlers,$handlers);
       $getHanders= $this->handlers;
       $func=function (MyContext $context) use($getHanders){
           foreach ($getHanders as $handler){
               $ret=$handler($context);
               if($ret){
                   $context->setHandlerResult($ret);
               }
           }

       };
       parent::addRoute($httpMethod, $route, $func); // TODO: Change the autogenerated stub
   }

}